version: "3"
services: 
  mysqldb:
    container_name: mysql
    image: mysql:5.7
    ports:
    - "32000:3306"
#    expose:
#    - "3306"
    volumes:
    - "$PWD/mysql-data/:/var/lib/mysql"
    environment:
      MYSQL_DATABASE: "db"
      # So you don't have to use root, but you can if you like
      MYSQL_USER: "riadh"
      # You can use whatever password you like
      MYSQL_PASSWORD: "password"
      # Password for root access
      MYSQL_ROOT_PASSWORD: "password"
volumes:
 mydb:
 
